permalink: /posts/:title
markdown: kramdown
  
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

name: Ander Iriondo Azpiri
languages: [en, eu, es]
default_lang: en
url: "https://anderiri2.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
enforce_ssl: anderiri2.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Ander Iriondo Azpiri, Researcher in AI & Robotics at Tekniker. 
  PhD in Artificial Intelligence and Robotics focusing on Deep Reinforcement Learning.
author: Ander Iriondo Azpiri
twitter_username: andeririondo # Assuming this is the username
google_scholar: Hy-Z3PoAAAAJ

collections:
  ml:
    output: true
  math:
    output: true

defaults:
  - scope:
      path: ""
      type: ml
    values:
      layout: post
  - scope:
      path: ""
      type: math
    values:
      layout: post
